#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    otherBattery,   sensorAnalog)
#pragma config(Sensor, in8,    armAngle,       sensorPotentiometer)
#pragma config(Sensor, dgtl12, skyriseClaw,    sensorDigitalOut)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           cubeIntake,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           lmDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lbDrive,       tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port4,           lfLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rDrive,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           skyriseArm,    tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port7,           rfLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rbLift,        tmotorVex393_MC29, PIDControl, encoderPort, I2C_2)
#pragma config(Motor,  port9,           lbLift,        tmotorVex393_MC29, PIDControl, reversed, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)
#include "Vex_Competition_Includes.h"
#include "enumerations.h"
#include "autonomous.h"
#include "lcd.h"
bool skills = false;
void pre_auton(){
	bLCDBacklight = true;
	clearLCD();
	displayLCDCenteredString(0, "Autonomous?");
	displayLCDCenteredString(1, "Red    1    Blue");
	while(true){
		if(nLCDButtons == MHLCDButtonLeft){
			initSkyriseIntakeWithTeamColor(MHTeamColorRed);
			break;
		}
		else if(nLCDButtons == MHLCDButtonRight){
			initSkyriseIntakeWithTeamColor(MHTeamColorBlue);
			break;
		}
		else if(nLCDButtons == MHLCDButtonCenter){
			skills = true;
			initSkyriseIntakeWithTeamColor(MHTeamColorBlue);
			break;
		}
	}
	clearLCD();
	bLCDBacklight = false;
}
task autonomous(){
	if(skills){
		basicDrive(MHMotorPowerMax, MHMotorPowerMax);
		wait1Msec(MHTimeOneSecond);
		stopDrive();
		return;
	}
	else{
		runAutonomousForTeamColor(roundColor);
	}
}
task usercontrol(){
	//Drive control
	bLCDBacklight = true;
	string first;
	string second;
	while(true){
		if(nMotorEncoder[lbLift] < 0){
			resetEncoders();
		}
		if(nLCDButtons != MHLCDButtonNone){
			resetEncoders();
		}
		sprintf(first, "%d", nMotorEncoder[lbLift]);
		sprintf(second, "%d", SensorValue[armAngle]);
		//displayLCDCenteredString(0, first);
		//displayLCDCenteredString(1, second);
		if(abs(vexRT[Ch2]) <= 30){
			stopDriveSide(MHRobotSideRight);
		}
		else{
			motor[rDrive] = vexRT[Ch2];
		}
		if(abs(vexRT[Ch3]) <= 30){
			stopDriveSide(MHRobotSideLeft);
		}
		else{
			motor[lmDrive] = motor[lbDrive] = vexRT[Ch3];
		}
		//Lift control
		if(vexRT[Btn6U]){
			lift(MHMotorPowerMax, MHLiftDirectionUp);
		}
		else if(vexRT[Btn6D]){
			lift(MHMotorPowerMax, MHLiftDirectionDown);
		}
		//If neither button is pressed, the lift must be stopped, or it will keep going
		else{
			lift(MHMotorPowerStop, MHLiftDirectionStop);
		}
		//Skyrise Intake
		if(vexRT[Btn8D]){
			SensorValue[skyriseClaw] = MHPneumaticPositionOpen;
		}
		else if(vexRT[Btn8R]){
			SensorValue[skyriseClaw] = MHPneumaticPositionClosed;
		}
		//Skyrise arm rotation
		static bool skyriseArmShouldStall = false;
		if(vexRT[Btn7R]){
			motor[skyriseArm] = MHMotorPowerMax;
		}
		else if(vexRT[Btn7L]){
			motor[skyriseArm] = -MHMotorPowerMax;
		}
		else if(vexRT[Btn7U]){
			if(skyriseArmShouldStall){
				skyriseArmShouldStall = false;
			}
			else{
				skyriseArmShouldStall = true;
			}
		}
		else if(skyriseArmShouldStall){
			motor[skyriseArm] = MHMotorPowerStall;
		}
		else{
			motor[skyriseArm] = MHMotorPowerStop;
		}
		//Cube Intake
		if(vexRT[Btn5U]){
			liftCube(MHLiftDirectionUp);
		}
		else if(vexRT[Btn5D]){
			liftCube(MHLiftDirectionDown);
		}
		else{
			liftCube(MHLiftDirectionStop);
		}
	}
}
