#pragma config(Sensor, in1,    otherBattery,   sensorAnalog)
#pragma config(Motor,  port1,           lfDrive,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lmDrive,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lbDrive,       tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port4,           lfLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rmDrive,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rbDrive,       tmotorVex393_MC29, openLoop, reversed, encoderPort, None)
#pragma config(Motor,  port7,           rfLift,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           rbLift,        tmotorVex393_MC29, openLoop, encoderPort, None)
#pragma config(Motor,  port9,           lbLift,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          rfDrive,       tmotorVex393_HBridge, openLoop, reversed, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"
#include "enumerations.h"
#include "autonomous.h"
#include "lcd.h"
void pre_auton(){

}
task autonomous(){

}
task usercontrol(){
	//Drive control
	bool rightDriveShouldStop;
	bool leftDriveShouldStop;
	//Determine if either drive should stop at the end of this iteration of the loop
	while(true){
		if(abs(vexRT[Ch2]) <= 30){
			rightDriveShouldStop = true;
		}
		else{
			rightDriveShouldStop = false;
		}
		if(abs(vexRT[Ch3]) <= 30){
			leftDriveShouldStop = true;
		}
		else{
			leftDriveShouldStop = false;
		}
		if(rightDriveShouldStop){
			stopDrive(MHRobotSideRight);
		}
		else{
			//For some reason, the motors aren't in sync with the joysticks, so we must reverse their direction
			motor[rfDrive] = motor[rmDrive] = motor[rbDrive] = vexRT[Ch2];
		}
		if(leftDriveShouldStop){
			stopDrive(MHRobotSideLeft);
		}
		else{
			motor[lfDrive] = motor[lmDrive] = motor[lbDrive] = vexRT[Ch3];
		}
		//Lift control
		if(vexRT[Btn6U]){
			lift(MHMotorPowerMax);
		}
		else if(vexRT[Btn6D]){
			lift(-MHMotorPowerMax);
		}
		//If neither button is pressed, the lift must be stopped, or it will keep going
		else{
			lift(MHMotorPowerStop);
		}
		//TODO: Add pneumatics and button single presses
	}
}
