#pragma config(Motor,  port1,           lLaunch,       tmotorVex393, openLoop)
#pragma config(Motor,  port2,           in,            tmotorVex393, openLoop)
#pragma config(Motor,  port3,           lfDrive,       tmotorVex393TurboSpeed, openLoop)
#pragma config(Motor,  port4,           lmDrive,       tmotorVex393TurboSpeed, openLoop)
#pragma config(Motor,  port5,           lbDrive,       tmotorVex393TurboSpeed, openLoop, reversed)
#pragma config(Motor,  port6,           rfDrive,       tmotorVex393TurboSpeed, openLoop)
#pragma config(Motor,  port7,           rmDrive,       tmotorVex393TurboSpeed, openLoop)
#pragma config(Motor,  port8,           rbDrive,       tmotorVex393TurboSpeed, openLoop, reversed)
#pragma config(Motor,  port10,          rLaunch,       tmotorVex393, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)
#include "Vex_Competition_Includes.c"
#include "constants.h"
#include "autonomous.h"
#include "lcd.h"

//Placeholder for the pre-autonomous task
void pre_auton(){
  //Display a generic idle screen on the LCD
  idleScreen();
}

//Placeholder for the autonomous task
task autonomous(){
  //Display a generic idle screen on the LCD
  idleScreen();
  AutonomousCodePlaceholderForTesting();
}

//Acutal driver control
task usercontrol(){
  idleScreen();
  //Make sure we're always running
  while(true){
    //Make the robot moves, if we want it to
    drive(MHControllerJoystickLeftYAxis, MHControllerJoystickRightYAxis);
  }
}