#pragma config(Motor,  port1,           in,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           lLaunch,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           lfDrive,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           lmDrive,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port5,           lbDrive,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port6,           rfDrive,       tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port7,           rmDrive,       tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           rbDrive,       tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port9,           rLaunch,       tmotorVex393_MC29, openLoop, reversed, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)
//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(15)
#pragma userControlDuration(105)
#include "Vex_Competition_Includes.h"
#include "constants.h"
#include "robot.h"
#include "lcd.h"

//Placeholder for the pre-autonomous task
void pre_auton(){
  //Display a generic idle screen on the LCD
  idleScreen();
}

//Placeholder for the autonomous task
task autonomous(){
  //Display a generic idle screen on the LCD
  idleScreen();
  //Just run all the cannon motors until the field tells us to stop
  fire();
}

//Acutal driver control
task usercontrol(){
  //Display a generic idle screen on the LCD
  idleScreen();
  //Make sure we're always running
  while(true){
    //Make the robot move, if we want it to
    drive(MHControllerJoystickLeftYAxisValue, MHControllerJoystickRightYAxisValue);
    if(MHControllerShoulderLeftButtonTopPressed){
      //If the top-left shoulder button (5U) is pressed, run the intake motors
      intake();
    }
    else if(MHControllerShoulderLeftButtonBottomPressed){
      //If the bottom-left shoulder button (5D) is pressed, run the intake motors backwards
      intakeInDirection(MHIntakeDirectionOuttake); //Don't worry about using this function. It runs the intake backwards
    }
    else{
      //If neither is pressed, stop the intake
      holdIntake();
    }
    if(MHControllerShoulderRightButtonTopPressed){
      //If the top-right shoulder button (6U) is pressed, run the launch motors
      launch();
    }
    else if(MHControllerShoulderRightButtonBottomPressed){
      //If the bottom-right shoulder button (6D) is pressed, run the launch motors in reverse
      launchInDirection(MHLaunchDirectionBackfire); // Don't worry about using this function. It runs the launch backwards
    }
    else{
      holdLaunch();
    }
  }
}
